### ISSUE TITLE
cargo installs fails to build (unstable feature lazy_cell)

### ISSUE THREAD

**Issue by apraga** [Cretezy/lazyjj#64]
Hi,

`cargo install` fails with the log below. Usign `--locked` does not help.
Any idea ?

Thanks,

`error[E0658]: use of unstable library feature 'lazy_cell'
 --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:5:5
  |
5 | use std::sync::LazyLock;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:20:25
   |
20 | static BUTTON_LABEL_RE: LazyLock<Regex> = LazyLock::new(||Regex::new(r#"(\(\w\))"#).unwrap());
   |                         ^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:20:43
   |
20 | static BUTTON_LABEL_RE: LazyLock<Regex> = LazyLock::new(||Regex::new(r#"(\(\w\))"#).unwrap());
   |                                           ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:23:17
   |
23 |     pub const YES: LazyLock<ButtonLabel> = LazyLock::new(|| ButtonLabel {
   |                    ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:23:41
   |
23 |     pub const YES: LazyLock<ButtonLabel> = LazyLock::new(|| ButtonLabel {
   |                                            ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:29:16
   |
29 |     pub const NO: LazyLock<ButtonLabel> = LazyLock::new(|| ButtonLabel {
   |                   ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:29:40
   |
29 |     pub const NO: LazyLock<ButtonLabel> = LazyLock::new(|| ButtonLabel {
   |                                           ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:20:43
   |
20 | static BUTTON_LABEL_RE: LazyLock<Regex> = LazyLock::new(||Regex::new(r#"(\(\w\))"#).unwrap());
   |                                           ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:23:41
   |
23 |     pub const YES: LazyLock<ButtonLabel> = LazyLock::new(|| ButtonLabel {
   |                                            ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/alexis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tui_confirm_dialog-0.2.3/src/confirm_dialog.rs:29:40
   |
29 |     pub const NO: LazyLock<ButtonLabel> = LazyLock::new(|| ButtonLabel {
   |                                           ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `tui_confirm_dialog` (lib) due to 10 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lazyjj v0.4.2`, intermediate artifacts can be found at `/tmp/cargo-installgYPWoO`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.w

**Comment by Cretezy** [comment]
Which version of Rust are you using? `LazyCell` was stabilized in 1.80 (https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html), released July 25th

**Comment by apraga** [comment]
It was 1.79. Updating to 1.80 fixed it, thanks !

**Comment by TRYKRB** [comment]
Then why doesn't it work with 1.84.1...

error[E0658]: use of unstable library feature 'lazy_cell'
  --> avm/src/lib.rs:12:5
   |
12 | use std::sync::LazyLock;
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> avm/src/lib.rs:15:22
   |
15 | pub static AVM_HOME: LazyLock<PathBuf> = LazyLock::new(|| {
   |                      ^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> avm/src/lib.rs:15:42
   |
15 | pub static AVM_HOME: LazyLock<PathBuf> = LazyLock::new(|| {
   |                                          ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> avm/src/lib.rs:15:42
   |
15 | pub static AVM_HOME: LazyLock<PathBuf> = LazyLock::new(|| {
   |                                          ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `avm` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `avm v0.30.1 (https://github.com/coral-xyz/anchor#16e166ca)`, intermediate artifacts can be found at `/tmp/cargo-installfswVFl`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
